spring:
  prifiles:
    active:
    - dev
---
spring:
  profiles: dev # 开发环境
  application:
    name: microservicecloud-config-atguigu-dev
---
spring:
  prifiles: test # 测试环境
  application:
    name: macroservicecloud-config-atguigu-test
# 请保存为UTF-8格式